create schema if not exists private;
revoke all on schema private from public;
create type public.merchant_status as enum ('pending','active','rejected','suspended');
create type public.member_role as enum ('admin','staff','operator');
create type public.order_status as enum ('placed','accepted','preparing','out_for_delivery','delivered','rejected','cancelled');
create table public.profiles(user_id uuid primary key references auth.users(id),display_name text not null default '' check(length(display_name)<=120),locale text not null default 'en' check(locale in ('en','pt-PT')),theme text not null default 'system' check(theme in ('light','dark','system')));
create table public.platform_admins(user_id uuid primary key references auth.users(id),active boolean not null default true);
create table public.merchants(id uuid primary key default gen_random_uuid(),name text not null check(length(trim(name)) between 2 and 120),slug text not null unique check(length(slug) between 3 and 48 and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and slug not in ('auth','account','merchant','platform','api','cart','checkout','orders','_next','favicon','robots','sitemap')),status public.merchant_status not null default 'pending',applicant_id uuid references auth.users(id),rejection_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.merchant_memberships(id uuid primary key default gen_random_uuid(),merchant_id uuid not null references public.merchants(id),user_id uuid not null unique references auth.users(id),role public.member_role not null,active boolean not null default true);
create table public.merchant_invitations(id uuid primary key default gen_random_uuid(),merchant_id uuid not null references public.merchants(id),email text not null check(email=lower(trim(email))),role public.member_role not null,token_hash text not null unique,expires_at timestamptz not null default now()+interval '7 days',accepted_at timestamptz,revoked_at timestamptz,delivery_state text not null default 'pending' check(delivery_state in ('pending','sent','failed')),created_at timestamptz not null default now());
create table public.stores(id uuid primary key default gen_random_uuid(),merchant_id uuid not null references public.merchants(id),name text not null check(length(trim(name)) between 2 and 120),street text not null check(length(trim(street)) between 2 and 200),city text not null check(length(trim(city)) between 1 and 100),state text not null check(length(trim(state)) between 1 and 100),zip_code text not null check(length(zip_code) between 1 and 20 and zip_code ~ '^[[:alnum:] -]+$'),phone text not null check(phone ~ '^\+[1-9][0-9]{6,14}$'),timezone text not null default 'Europe/Lisbon',active boolean not null default true,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(merchant_id,id));
create table public.products(id uuid primary key default gen_random_uuid(),merchant_id uuid not null,store_id uuid not null,name text not null check(length(trim(name)) between 2 and 120),description text not null default '' check(length(description)<=2000),price_minor integer not null check(price_minor between 1 and 99999999),available boolean not null default true,archived_at timestamptz,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(merchant_id,store_id) references public.stores(merchant_id,id),unique(merchant_id,store_id,id));
create table public.order_groups(id uuid primary key default gen_random_uuid(),customer_id uuid not null references auth.users(id),idempotency_key uuid not null,request_hash text not null,submitted_total_minor bigint not null check(submitted_total_minor>0 and submitted_total_minor<=989999990100),created_at timestamptz not null default now(),unique(customer_id,idempotency_key),unique(id,customer_id));
create table public.store_orders(id uuid primary key default gen_random_uuid(),group_id uuid not null,merchant_id uuid not null,store_id uuid not null,customer_id uuid not null,reference text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),store_name text not null,status public.order_status not null default 'placed',subtotal_minor bigint not null check(subtotal_minor>0),delivery jsonb not null,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(group_id,customer_id) references public.order_groups(id,customer_id),foreign key(merchant_id,store_id) references public.stores(merchant_id,id),unique(group_id,store_id),unique(id,merchant_id,store_id));
create table public.order_items(id uuid primary key default gen_random_uuid(),store_order_id uuid not null,merchant_id uuid not null,store_id uuid not null,product_id uuid not null,product_name text not null,unit_price_minor integer not null check(unit_price_minor>0),quantity integer not null check(quantity between 1 and 99),line_total_minor bigint generated always as (unit_price_minor::bigint*quantity) stored,foreign key(store_order_id,merchant_id,store_id) references public.store_orders(id,merchant_id,store_id),foreign key(merchant_id,store_id,product_id) references public.products(merchant_id,store_id,id),unique(store_order_id,product_id));
create table public.order_status_events(id uuid primary key default gen_random_uuid(),store_order_id uuid not null references public.store_orders(id),previous_status public.order_status,new_status public.order_status not null,actor_id uuid references auth.users(id),reason text check(length(reason)<=500),created_at timestamptz not null default now());
create table public.audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid,merchant_id uuid,action text not null,entity_type text not null,entity_id uuid,changed_fields text[] not null default '{}',created_at timestamptz not null default now());
create index on public.stores(merchant_id,created_at desc,id);
create index on public.products(merchant_id,store_id,created_at desc,id);
create index on public.merchants(status);
create index on public.merchant_memberships(merchant_id);
create index on public.merchant_invitations(merchant_id,expires_at);
create index on public.order_groups(customer_id,created_at desc);
create index on public.store_orders(merchant_id,status,created_at desc);
create index on public.store_orders(customer_id,created_at desc);
create index on public.store_orders(store_id);
create index on public.order_status_events(store_order_id,created_at);
create index on public.audit_events(merchant_id,created_at desc);

create function private.is_verified() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from auth.users where id=auth.uid() and email_confirmed_at is not null) $$;
create function private.aal2() returns boolean language sql stable as $$select coalesce(auth.jwt()->>'aal','')='aal2'$$;
create function private.customer_ok() returns boolean language sql stable security definer set search_path='' as $$select private.is_verified() and (private.aal2() or not exists(select 1 from auth.mfa_factors where user_id=auth.uid() and status='verified'))$$;
create function private.is_platform() returns boolean language sql stable security definer set search_path='' as $$select private.is_verified() and private.aal2() and exists(select 1 from public.platform_admins where user_id=auth.uid() and active)$$;
create function private.member_ok(mid uuid,roles public.member_role[] default array['admin','staff','operator']::public.member_role[],fulfillment boolean default false) returns boolean language sql stable security definer set search_path='' as $$select private.is_verified() and private.aal2() and exists(select 1 from public.merchant_memberships mm join public.merchants m on m.id=mm.merchant_id where mm.user_id=auth.uid() and mm.merchant_id=mid and mm.active and mm.role=any(roles) and (m.status='active' or (fulfillment and m.status='suspended')))$$;
create function private.require_member(mid uuid,roles public.member_role[] default array['admin','staff','operator']::public.member_role[],fulfillment boolean default false) returns void language plpgsql security definer set search_path='' as $$begin if not private.member_ok(mid,roles,fulfillment) then raise exception 'FORBIDDEN'; end if; end$$;
create function private.require_platform() returns void language plpgsql security definer set search_path='' as $$begin if not private.is_platform() then raise exception 'FORBIDDEN'; end if; end$$;
create function private.order_read(oid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.store_orders o where o.id=oid and ((o.customer_id=auth.uid() and private.customer_ok()) or private.member_ok(o.merchant_id,array['admin','staff','operator']::public.member_role[],true)))$$;

alter table public.profiles enable row level security;
alter table public.platform_admins enable row level security;
alter table public.merchants enable row level security;
alter table public.merchant_memberships enable row level security;
alter table public.merchant_invitations enable row level security;
alter table public.stores enable row level security;
alter table public.products enable row level security;
alter table public.order_groups enable row level security;
alter table public.store_orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_events enable row level security;
alter table public.audit_events enable row level security;
revoke all on all tables in schema public from anon,authenticated;
grant select on public.profiles,public.merchants,public.merchant_memberships,public.stores,public.products,public.order_groups,public.store_orders,public.order_items,public.order_status_events,public.audit_events to authenticated;
create policy own_profile on public.profiles for select to authenticated using(user_id=auth.uid() and private.customer_ok());
create policy merchant_read on public.merchants for select to authenticated using(private.is_platform() or private.member_ok(id,array['admin','staff','operator']::public.member_role[],true));
create policy membership_read on public.merchant_memberships for select to authenticated using(private.member_ok(merchant_id,array['admin']::public.member_role[]) or (user_id=auth.uid() and private.member_ok(merchant_id,array['admin','staff','operator']::public.member_role[],true)));
create policy stores_read on public.stores for select to authenticated using(private.member_ok(merchant_id,array['admin','staff','operator']::public.member_role[],true));
create policy products_read on public.products for select to authenticated using(private.member_ok(merchant_id));
create policy groups_read on public.order_groups for select to authenticated using(customer_id=auth.uid() and private.customer_ok());
create policy orders_read on public.store_orders for select to authenticated using((customer_id=auth.uid() and private.customer_ok()) or private.member_ok(merchant_id,array['admin','staff','operator']::public.member_role[],true));
create policy items_read on public.order_items for select to authenticated using(private.order_read(store_order_id));
create policy events_read on public.order_status_events for select to authenticated using(private.order_read(store_order_id));
create policy audit_read on public.audit_events for select to authenticated using((merchant_id is null and private.is_platform()) or private.member_ok(merchant_id,array['admin']::public.member_role[]));
grant usage on schema private to authenticated;
grant execute on function private.customer_ok(),private.member_ok(uuid,public.member_role[],boolean),private.is_platform(),private.order_read(uuid),private.aal2(),private.is_verified() to authenticated;

create function private.new_profile() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(user_id) values(new.id); return new; end$$;
create trigger new_profile after insert on auth.users for each row execute function private.new_profile();
create function private.touch() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now(); if to_jsonb(new) ? 'version' then new.version=old.version+1; end if; return new; end$$;
create trigger touch before update on public.merchants for each row execute function private.touch();
create trigger touch before update on public.stores for each row execute function private.touch();
create trigger touch before update on public.products for each row execute function private.touch();
create trigger touch before update on public.store_orders for each row execute function private.touch();
create function private.immutable_owner() returns trigger language plpgsql set search_path='' as $$begin if new.merchant_id<>old.merchant_id or (to_jsonb(new)->>'store_id') is distinct from (to_jsonb(old)->>'store_id') then raise exception 'FORBIDDEN'; end if; return new; end$$;
create trigger immutable_owner before update on public.stores for each row execute function private.immutable_owner();
create trigger immutable_owner before update on public.products for each row execute function private.immutable_owner();
create function private.validate_timezone() returns trigger language plpgsql set search_path='' as $$begin if not exists(select 1 from pg_catalog.pg_timezone_names where name=new.timezone) then raise exception 'VALIDATION_ERROR'; end if; return new; end$$;
create trigger timezone before insert or update on public.stores for each row execute function private.validate_timezone();
create function private.immutable_slug() returns trigger language plpgsql set search_path='' as $$begin if new.slug<>old.slug then raise exception 'FORBIDDEN'; end if; return new; end$$;
create trigger immutable_slug before update on public.merchants for each row execute function private.immutable_slug();
create function private.audit() returns trigger language plpgsql security definer set search_path='' as $$declare n jsonb=to_jsonb(new); o jsonb=case when tg_op='UPDATE' then to_jsonb(old) else '{}'::jsonb end; mid uuid; fields text[]; begin mid=case when tg_table_name='merchants' then new.id else (n->>'merchant_id')::uuid end; select array_agg(key order by key) into fields from jsonb_each(n) where value is distinct from o->key and key not in ('token_hash','delivery','email'); insert into public.audit_events(actor_id,merchant_id,action,entity_type,entity_id,changed_fields) values(auth.uid(),mid,tg_op,tg_table_name,new.id,coalesce(fields,'{}')); return new; end$$;
create trigger audit after insert or update on public.merchants for each row execute function private.audit();
create trigger audit after insert or update on public.stores for each row execute function private.audit();
create trigger audit after insert or update on public.products for each row execute function private.audit();
create trigger audit after insert or update on public.merchant_memberships for each row execute function private.audit();
create trigger audit after insert or update on public.merchant_invitations for each row execute function private.audit();
create function private.exclusive_role() returns trigger language plpgsql security definer set search_path='' as $$begin perform 1 from auth.users where id=new.user_id for update; if (tg_table_name='platform_admins' and exists(select 1 from public.merchant_memberships where user_id=new.user_id)) or (tg_table_name='merchant_memberships' and exists(select 1 from public.platform_admins where user_id=new.user_id)) then raise exception 'FORBIDDEN'; end if; return new; end$$;
create trigger exclusive_role before insert or update on public.platform_admins for each row execute function private.exclusive_role();
create trigger exclusive_role before insert or update on public.merchant_memberships for each row execute function private.exclusive_role();
